//  MOCK QUESTIONS 
export const mockQuestions = [
  {
    id: 1,
    title: "How do I solve quadratic equations using the quadratic formula?",
    subject: "Mathematics",
    subjectIcon: "",
    description:
      "I'm struggling with quadratic equations in my Algebra 2 class. I understand factoring simple ones but when the numbers get messy I'm completely lost. Can someone walk me through the quadratic formula step by step with a real example?",
    level: "High School",
    grade: "Grade 10",
    isPaid: false,
    pricePerHour: 0,
    deadline: "2026-07-06",
    urgency: "medium",
    responses: 3,
    studentId: 1,
    studentName: "Amara K.",
    postedAt: "2026-07-03T10:00:00Z",
    status: "open",
    tags: ["algebra", "quadratic", "formula"],
  },
  {
    id: 2,
    title: "Need help debugging my Python Flask REST API — 404 on all routes",
    subject: "Coding",
    subjectIcon: "",
    description:
      "I built a small Flask app for my uni project. When I run it locally everything works fine, but when I deploy to Render I get 404 on every single route. I've been stuck for two days. Will share my code.",
    level: "University",
    grade: "Year 2 CS",
    isPaid: true,
    pricePerHour: 18,
    deadline: "2026-07-05",
    urgency: "high",
    responses: 5,
    studentId: 2,
    studentName: "Daniel O.",
    postedAt: "2026-07-03T08:30:00Z",
    status: "open",
    tags: ["python", "flask", "api", "deployment"],
  },
  {
    id: 3,
    title: "Explain the causes and consequences of the French Revolution",
    subject: "History",
    subjectIcon: "",
    description:
      "My essay is due Friday and I need to understand the social, economic and political causes of the French Revolution and how they connect. Also what were the long-term consequences for Europe?",
    level: "High School",
    grade: "Grade 11",
    isPaid: true,
    pricePerHour: 12,
    deadline: "2026-07-05",
    urgency: "high",
    responses: 2,
    studentId: 3,
    studentName: "Sophie L.",
    postedAt: "2026-07-02T18:00:00Z",
    status: "open",
    tags: ["french revolution", "european history", "essay"],
  },
  {
    id: 4,
    title: "What is the difference between mitosis and meiosis?",
    subject: "Biology",
    subjectIcon: "",
    description:
      "I keep mixing them up in my exams. I need a clear, simple explanation with a comparison table and memory tricks if possible. This is for my Grade 9 science class.",
    level: "High School",
    grade: "Grade 9",
    isPaid: false,
    pricePerHour: 0,
    deadline: "2026-07-08",
    urgency: "low",
    responses: 7,
    studentId: 4,
    studentName: "Keita N.",
    postedAt: "2026-07-01T14:00:00Z",
    status: "open",
    tags: ["cell division", "mitosis", "meiosis", "biology"],
  },
  {
    id: 5,
    title: "Help me understand supply and demand elasticity — with real examples",
    subject: "Economics",
    subjectIcon: "",
    description:
      "I'm an adult learner taking an online economics certificate. The textbook explanation is too abstract. Can someone explain price elasticity of demand using everyday products I'd recognize?",
    level: "Adult Learner",
    grade: "Certificate Program",
    isPaid: true,
    pricePerHour: 20,
    deadline: "2026-07-10",
    urgency: "low",
    responses: 1,
    studentId: 5,
    studentName: "Rachel T.",
    postedAt: "2026-07-03T09:00:00Z",
    status: "open",
    tags: ["economics", "elasticity", "supply", "demand"],
  },
  {
    id: 6,
    title: "How do I conjugate French verbs in the passé composé?",
    subject: "Languages",
    subjectIcon: "",
    description:
      "I'm learning French as a hobby. I can do present tense but passé composé is confusing me — especially when to use avoir vs être and the agreement rules. Please help with clear examples.",
    level: "Adult Learner",
    grade: "Self-Learner",
    isPaid: false,
    pricePerHour: 0,
    deadline: "2026-07-12",
    urgency: "low",
    responses: 4,
    studentId: 6,
    studentName: "Marco F.",
    postedAt: "2026-07-02T20:00:00Z",
    status: "in-progress",
    tags: ["french", "verb conjugation", "grammar"],
  },
  {
    id: 7,
    title: "I need to understand Newton's 3 laws with worked physics problems",
    subject: "Physics",
    subjectIcon: "",
    description:
      "My exam is in 3 days and Newton's laws are worth 30% of the paper. I understand the theory a bit but I freeze on actual calculation problems. Need someone to do 5–6 practice problems with me.",
    level: "High School",
    grade: "Grade 12",
    isPaid: true,
    pricePerHour: 15,
    deadline: "2026-07-06",
    urgency: "high",
    responses: 6,
    studentId: 7,
    studentName: "Priya S.",
    postedAt: "2026-07-03T07:00:00Z",
    status: "open",
    tags: ["newton", "physics", "mechanics", "exam prep"],
  },
  {
    id: 8,
    title: "Can someone proofread my university personal statement?",
    subject: "Writing",
    subjectIcon: "",
    description:
      "I'm applying to study medicine. My personal statement is done but I'm not confident about the structure and whether I'm hitting the right points. I'd love feedback from someone who knows what admissions tutors look for.",
    level: "High School",
    grade: "Grade 13 / A-Level",
    isPaid: true,
    pricePerHour: 25,
    deadline: "2026-07-07",
    urgency: "medium",
    responses: 3,
    studentId: 8,
    studentName: "James W.",
    postedAt: "2026-07-03T11:00:00Z",
    status: "open",
    tags: ["personal statement", "medicine", "writing", "university"],
  },
  {
    id: 9,
    title: "Struggling with integration by parts — calculus help needed",
    subject: "Mathematics",
    subjectIcon: "",
    description:
      "I'm a first-year maths student and integration by parts is destroying me. The formula makes sense but I never know how to choose u and dv. Need step-by-step help with at least 3 different examples.",
    level: "University",
    grade: "Year 1 Maths",
    isPaid: true,
    pricePerHour: 22,
    deadline: "2026-07-08",
    urgency: "medium",
    responses: 4,
    studentId: 2,
    studentName: "Daniel O.",
    postedAt: "2026-07-02T15:00:00Z",
    status: "open",
    tags: ["calculus", "integration", "university maths"],
  },
  {
    id: 10,
    title: "What are the key themes in 'To Kill a Mockingbird'?",
    subject: "Literature",
    subjectIcon: "",
    description:
      "I have a class discussion tomorrow and I haven't finished the book  I need a quick summary of the main themes — justice, racism, moral growth — and some good quotes to reference.",
    level: "High School",
    grade: "Grade 10",
    isPaid: false,
    pricePerHour: 0,
    deadline: "2026-07-04",
    urgency: "high",
    responses: 9,
    studentId: 4,
    studentName: "Keita N.",
    postedAt: "2026-07-03T12:30:00Z",
    status: "open",
    tags: ["literature", "novel", "themes", "essay"],
  },
];

//  MOCK TUTORS / HELPERS 
export const mockTutors = [
  {
    id: 1,
    name: "Dr. Fatima Al-Hassan",
    avatar: "",
    avatarColor: "#6C63FF",
    bio: "Former university lecturer with 8 years of teaching experience in mathematics and physics. I make complex concepts feel simple and achievable. I love working with students who are ready to put in the effort!",
    subjects: ["Mathematics", "Physics", "Statistics"],
    level: "University",
    isVerifiedTutor: true,
    rating: 4.9,
    reviewCount: 134,
    rateMin: 18,
    rateMax: 30,
    helpedFree: 22,
    responseTime: "< 1 hour",
    languages: ["English", "Arabic"],
    reviews: [
      { author: "Sophie L.", text: "Absolutely brilliant. Explained calculus in a way I finally understand!", rating: 5 },
      { author: "Priya S.", text: "Patient, clear, and incredibly knowledgeable. Worth every penny.", rating: 5 },
      { author: "James W.", text: "Helped me pass my finals. Cannot recommend enough.", rating: 5 },
    ],
  },
  {
    id: 2,
    name: "Marcus Chen",
    avatar: "",
    avatarColor: "#FF6584",
    bio: "Full-stack developer by day, coding tutor by passion. I've been coding since I was 14 and I genuinely love helping people break through that 'I don't get it' wall. Specialise in Python, JavaScript, and web dev.",
    subjects: ["Coding", "Mathematics", "Computer Science"],
    level: "University / Professional",
    isVerifiedTutor: true,
    rating: 4.8,
    reviewCount: 89,
    rateMin: 20,
    rateMax: 35,
    helpedFree: 31,
    responseTime: "< 2 hours",
    languages: ["English", "Mandarin"],
    reviews: [
      { author: "Daniel O.", text: "Fixed my Flask deployment issue in 45 minutes. Legend.", rating: 5 },
      { author: "Amara K.", text: "Super patient with beginners. Great communicator.", rating: 5 },
      { author: "Marco F.", text: "Explained React hooks like it was nothing. Really helped.", rating: 4 },
    ],
  },
  {
    id: 3,
    name: "Isabelle Moreau",
    avatar: "",
    avatarColor: "#43C59E",
    bio: "Native French speaker and MA graduate in Modern Languages. I teach French, Spanish and help with essay writing and academic English. I believe language learning should feel fun, not scary.",
    subjects: ["Languages", "Literature", "Writing"],
    level: "All levels",
    isVerifiedTutor: true,
    rating: 4.7,
    reviewCount: 61,
    rateMin: 14,
    rateMax: 22,
    helpedFree: 18,
    responseTime: "< 3 hours",
    languages: ["English", "French", "Spanish"],
    reviews: [
      { author: "Marco F.", text: "My French improved SO much after just 2 sessions!", rating: 5 },
      { author: "Rachel T.", text: "Very structured approach. Lovely teacher.", rating: 5 },
      { author: "Keita N.", text: "Helped me with my English essay — got an A!", rating: 4 },
    ],
  },
  {
    id: 4,
    name: "Ayaan Patel",
    avatar: "",
    avatarColor: "#FF9F43",
    bio: "Biology & Chemistry PhD student. I help high school and uni students who feel overwhelmed by science subjects. I break things down visually — diagrams, flowcharts, memory devices — whatever it takes.",
    subjects: ["Biology", "Chemistry", "Science"],
    level: "High School / University",
    isVerifiedTutor: false,
    rating: 4.6,
    reviewCount: 43,
    rateMin: 10,
    rateMax: 18,
    helpedFree: 45,
    responseTime: "< 4 hours",
    languages: ["English", "Hindi"],
    reviews: [
      { author: "Keita N.", text: "Mitosis vs meiosis finally makes sense! Great tutor.", rating: 5 },
      { author: "Priya S.", text: "Very thorough and patient. Great diagrams too.", rating: 4 },
      { author: "Sophie L.", text: "Helped me with chemistry equilibrium. Really solid.", rating: 5 },
    ],
  },
  {
    id: 5,
    name: "Zara Williams",
    avatar: "",
    avatarColor: "#A29BFE",
    bio: "Third-year History & Economics student at university. I remember what it's like to be in high school feeling confused, and I genuinely love helping other students. I offer free help whenever I can!",
    subjects: ["History", "Economics", "Social Studies"],
    level: "High School / Adult Learner",
    isVerifiedTutor: false,
    rating: 4.5,
    reviewCount: 27,
    rateMin: 8,
    rateMax: 14,
    helpedFree: 62,
    responseTime: "< 5 hours",
    languages: ["English"],
    reviews: [
      { author: "Amara K.", text: "So helpful! Explained the causes of WW1 really clearly.", rating: 5 },
      { author: "Rachel T.", text: "Great for economics concepts. Very relatable tutor.", rating: 4 },
      { author: "James W.", text: "Helped me brainstorm my personal statement. Really kind.", rating: 5 },
    ],
  },
];

//  MOCK USERS 
export const mockUsers = {
  student: {
    id: 1,
    name: "amara",
    email: "amara@example.com",
    role: "student",
    avatar: "",
    avatarColor: "#6C63FF",
    level: "High School — Grade 10",
    joinedAt: "2026-01-15",
    myQuestions: [1],
  },
  tutor: {
    id: 2,
    name: "marcus",
    email: "marcus@example.com",
    role: "tutor",
    avatar: "",
    avatarColor: "#FF6584",
    subjects: ["Coding", "Mathematics", "Computer Science"],
    rating: 4.8,
    totalEarned: 1240,
    helpedFree: 31,
    activeJobs: [2, 9],
    joinedAt: "2025-09-10",
  },
  admin: {
    id: 3,
    name: "admin",
    email: "admin@jonne.com",
    role: "admin",
    avatar: "",
    avatarColor: "#2C3E50",
    joinedAt: "2024-01-01",
  },
};

//  MOCK TRANSACTIONS 
export const mockPlatformTransactions = [
  {
    id: "TXN-8821",
    studentName: "Amara K.",
    tutorName: "Dr. Fatima Al-Hassan",
    amount: 20,
    date: "2026-07-01T10:00:00Z",
    status: "completed",
    subject: "Mathematics",
  },
  {
    id: "TXN-8822",
    studentName: "Sophie L.",
    tutorName: "Marcus Chen",
    amount: 35,
    date: "2026-07-03T09:45:00Z",
    status: "completed",
    subject: "Coding",
  },
  {
    id: "TXN-8823",
    studentName: "Daniel O.",
    tutorName: "Dr. Fatima Al-Hassan",
    amount: 18,
    date: "2026-07-03T08:00:00Z",
    status: "pending",
    subject: "Coding",
  },
  {
    id: "TXN-8824",
    studentName: "Rachel T.",
    tutorName: "Marcus Chen",
    amount: 60,
    date: "2026-07-04T14:20:00Z",
    status: "completed",
    subject: "Economics",
  },
  {
    id: "TXN-8825",
    studentName: "Priya S.",
    tutorName: "Isabelle Moreau",
    amount: 15,
    date: "2026-07-02T11:15:00Z",
    status: "refunded",
    subject: "Languages",
  }
];

//  MOCK REPORTS 
export const mockReports = [
  {
    id: 1,
    type: "question",
    targetId: 2,
    targetTitle: "Need help debugging my Python Flask REST API",
    reason: "Contains spam links in description",
    reportedBy: "Dr. Fatima Al-Hassan",
    reportedAt: "2026-07-03T11:20:00Z",
    status: "pending"
  },
  {
    id: 2,
    type: "review",
    targetId: 1,
    targetTitle: "Review by Sophie L. on Dr. Fatima Al-Hassan",
    reason: "Abusive language / harassment",
    reportedBy: "Dr. Fatima Al-Hassan",
    reportedAt: "2026-07-04T09:10:00Z",
    status: "pending"
  },
  {
    id: 3,
    type: "user",
    targetId: 4,
    targetTitle: "Keita N. (Student)",
    reason: "Posting copy-pasted homework assignments in bulk",
    reportedBy: "Isabelle Moreau",
    reportedAt: "2026-07-02T15:30:00Z",
    status: "resolved"
  }
];


//  SUBJECTS LIST 
export const subjects = [
  { label: "Mathematics", icon: "" },
  { label: "Physics", icon: "" },
  { label: "Biology", icon: "" },
  { label: "Chemistry", icon: "" },
  { label: "History", icon: "" },
  { label: "Economics", icon: "" },
  { label: "Coding", icon: "" },
  { label: "Languages", icon: "" },
  { label: "Literature", icon: "" },
  { label: "Writing", icon: "" },
  { label: "Science", icon: "" },
  { label: "Geography", icon: "" },
  { label: "Art", icon: "" },
  { label: "Music", icon: "" },
  { label: "Other", icon: "" },
];

export const educationLevels = [
  "Primary School",
  "High School — Grade 7",
  "High School — Grade 8",
  "High School — Grade 9",
  "High School — Grade 10",
  "High School — Grade 11",
  "High School — Grade 12",
  "High School — Grade 13 / A-Level",
  "University — Year 1",
  "University — Year 2",
  "University — Year 3",
  "University — Year 4+",
  "Adult Learner",
  "Self-Learner",
  "Certificate / Diploma Program",
];
